# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qpmWXEg4nUy6iQfdML82rcf8SGu3aUsK
"""

# Subimos el archivo ventas.csv desde nuestra computadora a Colab
from google.colab import files
archivo = files.upload()

import pandas as pd
import matplotlib.pyplot as plt

# Cargamos el dataset de ventas
# pd.read_csv lee el archivo CSV y lo convierte en una tabla
df = pd.read_csv('ventas.csv')

# Mostramos las primeras filas para verificar que cargó bien
print("Primeras filas del dataset:")
print(df.head())

# Convertimos la columna fecha a formato de fecha real
# Esto nos permite agrupar por mes después
df['fecha'] = pd.to_datetime(df['fecha'])
df['mes'] = df['fecha'].dt.month

# Ventas totales: sumamos todos los montos
total_ventas = df['monto_total'].sum()
print(f"Ventas totales del año: ${total_ventas:,}")

# Producto más vendido: sumamos cantidad por producto y buscamos el mayor
producto_mas_vendido = df.groupby('producto')['cantidad'].sum().idxmax()
print(f"Producto más vendido: {producto_mas_vendido}")

# Ventas por mes: sumamos el monto total agrupando por mes
ventas_por_mes = df.groupby('mes')['monto_total'].sum()
print("\nVentas por mes:")
print(ventas_por_mes)

# Creamos el gráfico de evolución de ventas por mes
plt.figure(figsize=(10, 5))
plt.plot(ventas_por_mes.index, ventas_por_mes.values, marker='o', color='blue')

# Títulos y etiquetas
plt.title('Evolución de Ventas por Mes - 2024')
plt.xlabel('Mes')
plt.ylabel('Monto Total ($)')
plt.xticks(range(1, 13), ['Ene','Feb','Mar','Abr','May','Jun',
                            'Jul','Ago','Sep','Oct','Nov','Dic'])
plt.grid(True)

# Guardamos el gráfico como imagen
# Este archivo después lo ponemos en la carpeta /resultados del repo
plt.savefig('grafico_ventas.png')
plt.show()
print("Gráfico guardado correctamente")

# Descargamos el gráfico a nuestra computadora
from google.colab import files
files.download('grafico_ventas.png')